### ISSUE TITLE
Translation platform

### ISSUE THREAD

**Issue by milotype** [rafaelmardojai/share-preview#53]
Please decide upon the translation platforms: **Hosted Weblate** or **Transifex**!

Recently I got emails about **Transifex notifications**, but there is just one file: _share-preview_po-share-preview-pot--master_en.po_. There are no translated languages!

On the other hand most translations exist at **Hosted Weblate**, which you specify in the section [Translations](https://github.com/rafaelmardojai/share-preview#translations) of the `ReadMe.md` file.

My suggestion:
Get rid of Transifex! IMO, Hosted Weblate is better anyhow.

Cheers,
Milo

**Comment by rafaelmardojai** [comment]
Well the app was in transifex since a long time ago, but never was published in the readme.

I recently decided to move it to weblate since I just discovered that I can keep requesting libre hosting for other apps in my account (something that wasn't really clear in the weblate UI).

So I removed all the content in transifex and updated the project description to point that it was moved to weblate, so if someone was using it, it wouldn't just disappear.

So yeah, weblate is the official place, and I will remove the app from transifex soon.
