### ISSUE TITLE
Warn users using relative URLs on Twitter

### ISSUE THREAD

**Issue by TheEvilSkeleton** [rafaelmardojai/share-preview#64]
Share Preview seems to display images with relative URLs, although Twitter does not support this.

![](https://github.com/rafaelmardojai/share-preview/assets/50847364/d77f1867-6ab3-490c-ab17-2a99db504fd9)

Notice that the image isn't shown.

On Share Preview, it looks like this:

![](https://github.com/rafaelmardojai/share-preview/assets/50847364/e61e024d-3783-4144-8689-fd11c522019a)

Where it shows the image.

---

As a solution, I'd make it warn the user when the website is using relative path, rather than a URL.

**Comment by rafaelmardojai** [comment]
The app has a mechanism to warn about unsupported formats but Twitter is set to support WebP since that is what is documented, so the issue might be somewhere else.

Checking Twitter docs again, it seems to say that urls can't be relative. Share Preview will convert all relative urls to absolute ones without further handling so that can be the problem.

**Comment by TheEvilSkeleton** [comment]
Thanks. I changed the title and description to reflect that
